version: '3'
services:

  server-app:
    image: pubsub-notification-consumer
    networks:
      pubsubmesh:
        aliases:
          - server-app
    environment:  
      - INSTANA_DEV=1
      - SERVER_PORT=8080
    expose:
      - "8080"
    ports:
      - "8080:8080"

  agent:
    image: instana/agent
    pid: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
      - ./agent/configuration-sdk.yaml:/opt/instana/agent/configuration-sdk.yaml
    networks:
      pubsubmesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=${agent_endpoint}
      - INSTANA_AGENT_ENDPOINT_PORT=${agent_endpoint_port:-443}
      - INSTANA_DOWNLOAD_KEY=${download_key}
      - INSTANA_AGENT_KEY=${agent_key}
      - INSTANA_AGENT_ZONE=${agent_zone:-pubsub-push-demo}
    expose:
      - "42699"

networks:
  pubsubmesh: {}
